redis-0: redis-server ./7000/redis.conf
redis-1: redis-server ./7001/redis.conf
redis-2: redis-server ./7002/redis.conf
redis-3: redis-server ./7003/redis.conf
redis-4: redis-server ./7004/redis.conf
redis-5: redis-server ./7005/redis.conf
redis-6: redis-server ./7006/redis.conf
redis-7: redis-server ./7007/redis.conf
